#!/bin/sh
set -eu

mkdir -p precompiled
{
   cat ../common/conditional.txt
   cat ../common/longcomment.txt
   cat ../common/dump.txt
   cat ../common/fixpt-math-lib.fs
   cat ../common/disassembler-m0.txt
   cat ../common/assembler-m0.txt
   cat basisdefinitions.txt

} > included.fs

../thumbulator/buildcore ../thumbulator/thumbulator-palanqin mecrisp-stellaris-palanqin.bin included.fs stelaqin.bin
