#!/bin/sh
set -eu

# Precompiled contents:

cat ../common/fixpt-math-lib.fs \
    ../common/disassembler-m0.txt \
    ../common/assembler-m0.txt \
    ../common/multitask.txt \
    cycles.txt \
    ../common/dump.txt \
    usb-rp2040.txt >included.txt
cat included.txt usbterm_as_default.txt > included-usb.txt

./buildcore-pico ../thumbulator/thumbulator-rp2040 mecrisp-stellaris-pico-core.bin included.txt mecrisp-stellaris-pico-core-with-tools.bin
./buildcore-pico ../thumbulator/thumbulator-rp2040 mecrisp-stellaris-pico-core.bin included-usb.txt mecrisp-stellaris-pico-core-with-tools-usb.bin

# Generate files for flash programming

dd if=/dev/zero bs=1 count=3840 of=padding.bin # Pad stage loader block to the next 4 kb border

for f in '' -with-tools -with-tools-usb
do
	cat tools/launchpad_boot_crc.bin padding.bin mecrisp-stellaris-pico-core$f.bin > mecrisp-stellaris-pico$f.bin
	tools/uf2conv.py --family 0xE48BFF56 --base 0x10000000 mecrisp-stellaris-pico$f.bin -o mecrisp-stellaris-pico$f.uf2
done
